application: pinkbot-ircbot-partytime-034
version: 1
runtime: php
api_version: 1

handlers:
- url: /
	script: pinkbot.php

- url: /testStrings
	script: testStrings.php
  

# Serve php scripts.
# - url: /([^/]+\.php)$
#   script: \1

